In [55]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

In [56]:
# 1. Create a Pandas Series named sales containing the values 120, 150, 180 and 210.



sales = pd.Series([120,150,180,210])

sales

0    120
1    150
2    180
3    210
dtype: int64

In [57]:
# 2. For the Series below, write the command that displays only the stored data values.

marks = Series([72, 81, 69, 90])
marks.values

array([72, 81, 69, 90])

In [58]:
# 3. For the same Series marks, write the command that displays its index.
marks.index

RangeIndex(start=0, stop=4, step=1)

In [59]:
# 4. Create a Series of temperatures 28, 31, 30 and 29 using the index labels Mon, Tue, Wed and Thu.
temperatures = Series((28, 31, 30, 29), index=['Mon', 'Tue', 'Wed', 'Thu'])
temperatures

Mon    28
Tue    31
Wed    30
Thu    29
dtype: int64

In [60]:
# 5. Given the Series below, write the expression to retrieve the population value for Jaipur.
population = Series([35, 42, 31], index=['Delhi','Mumbai','Jaipur'])
population['Jaipur']

np.int64(31)

In [61]:
# 6. Write a Boolean-filtering expression to display only the values greater than 50 from the Series score.
score = Series([35, 68, 44, 79, 52])
score=[score>50]
score

[0    False
 1     True
 2    False
 3     True
 4     True
 dtype: bool]

In [62]:
# 7. Using the Series below, write an expression to check whether the label Chemistry is present in its index.
subjects = Series([76, 83, 91], index=['Physics','Chemistry','Maths'])
'Chemistry' in subjects.index

True

In [63]:
# 8. Write the Pandas Series method that converts a Series into a Python dictionary.
subjects.to_dict()

{'Physics': 76, 'Chemistry': 83, 'Maths': 91}

In [64]:
# 9. Convert the following dictionary into a Pandas Series named price_series.


prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}

price_series = pd.Series(prices)

print(price_series)

Pen          10
Notebook     55
Bag         700
dtype: int64

In [65]:
# 10. When a dictionary is converted into a Series without separately specifying an index, what becomes the Series index?
price_series.index

Index(['Pen', 'Notebook', 'Bag'], dtype='object')

In [66]:
# 11. In the following code, identify the label that will have a missing value.
data = {'A': 10, 'B': 20, 'C': 30}
s = Series(data, index=['A','B','C','D'])
s

A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64

In [67]:
# 12. Write a Pandas expression using isnull to identify missing values in a Series named.
s.isnull()

A    False
B    False
C    False
D     True
dtype: bool

In [68]:
# 13. Write a Pandas expression using notnull to identify non-missing values in a Series named s.
s.notnull()

A     True
B     True
C     True
D    False
dtype: bool

In [69]:
# 14. Assign the name Monthly Sales to a Series named sales.
sales.name="Monthly Sales"
sales

0    120
1    150
2    180
3    210
Name: Monthly Sales, dtype: int64

In [70]:
# 15. Assign the name Month to the index of a Series named sale.
sales.name="Month"
sales

0    120
1    150
2    180
3    210
Name: Month, dtype: int64

In [71]:
# 16. Predict which labelled entries will be returned by the following expression.
s = Series([18, 45, 27, 61], index=['P','Q','R','S'])
s[s > 30]

Q    45
S    61
dtype: int64

In [72]:
# 17. Predict the result of each membership test. Remember that membership is checked against the Series index.
s = Series([500, 600, 700], index=['East','West','North'])
'West' in s
500 in s

False

In [73]:
# 18. A dictionary contains data for Delhi, Pune and Kochi. Create a Series using the ordered index Delhi, Kochi, Pune, Chennai. State which label will receive NaN.
city_data = {'Delhi': 80, 'Pune': 65, 'Kochi': 70}
cities = Series(city_data, index=['Delhi', 'pune', 'Kochi'])
cities

Delhi    80.0
pune      NaN
Kochi    70.0
dtype: float64

In [74]:
# 19. The following Series contains one missing value. State the Boolean output conceptually produced by pd.isnull(s) for W, X, Y and Z.
s = Series({'W': 5, 'X': 10, 'Y': 15}, index=['W','X','Y','Z'])
s.isnull()

W    False
X    False
Y    False
Z     True
dtype: bool

In [75]:
# 20. For Question 19, state the Boolean output conceptually produced by pd.notnull(s) for W, X, Y and Z.
s.notnull()

W     True
X     True
Y     True
Z    False
dtype: bool

In [76]:
# 21. Predict the result of adding the following two Series. Show the result for labels A, B and C.
s1 = Series([10, 20, 30], index=['A','B','C'])
s2 = Series([1, 2, 3], index=['C','A','B'])
s1 + s2

A    12
B    23
C    31
dtype: int64

In [77]:
# 22. Explain why the following addition produces a missing value for some labels even though both Series contain numeric data.
# Pandas performs addition based on index labels, not just on the position of the values.
s1 = Series({'A': 12, 'B': 18})
s2 = Series({'B': 5, 'C': 9})
s1 + s2

A     NaN
B    23.0
C     NaN
dtype: float64

In [78]:
# 23. Write code to convert the following Series to a dictionary named stock_dict and then reconstruct a new Series named stock2 from that dictionary.
stock = Series([25, 40, 18], index=['Item1','Item2','Item3'])
stock_dict = stock.to_dict()
stock2 = Series(stock_dict)
stock

Item1    25
Item2    40
Item3    18
dtype: int64

In [79]:
#24. Create a Series from the dictionary below using the index order History, English, Science, Maths. Then write an expression to display only values greater than 70.
marks = {'Maths': 88, 'Science': 74, 'English': 69, 'History': 81}
marks = Series(marks, index=['History', 'English', 'Science', 'Maths'])
marks[marks>70]

History    81
Science    74
Maths      88
dtype: int64

In [80]:
# 25. A Series is named Revenue and its index is named Branch. Write the two assignment statements needed to apply these names to a Series object called rev.
rev = Series([120,150,140,130])
rev.name = "Revenue"
rev.index.name = "Branch"

In [82]:
# 26. Analyse the following program. Determine the final result of total for every label and explain how Pandas index alignment determines each value.
north = Series({'Jan': 40, 'Feb': 55, 'Mar': 60})
south = Series({'Feb': 20, 'Mar': 25, 'Apr': 30})
total = north + south
total

Apr     NaN
Feb    75.0
Jan     NaN
Mar    85.0
dtype: float64

In [83]:
# 27. Study the code and answer all parts: (a) Which label contains NaN? (b) What does pd.isnull(result) returnfor that label? (c) Why is the missing value created? (d) Which labels retain actual numeric values?
d = {'Red': 12, 'Blue': 18, 'Green': 24}
labels = ['Green', 'Red', 'Yellow', 'Blue']

result = Series(d, index=labels)

In [84]:
# 28. Without running the code, trace the complete transformation and state the index and values of s2. Thenstate whether s and s2 represent the same labelled data.
s = Series([90, 75, 82], index=['Ravi', 'Aman', 'Neha'])
d = s.to_dict()
s2 = Series(d)
s2

Ravi    90
Aman    75
Neha    82
dtype: int64

In [86]:
# 29. Write a short Pandas program that creates a labelled Series for four products and sales, displays its valuesand index, selects one label, filters sales above 500, checks whether a label exists, and converts the Series to adictionary.
sales = Series([120,230,245,579],index=['pen', 'pencil', 'notebook', 'erasor'])
sales.index
sales.values
sales['pencil']
sales[sales>500]
'pencil' in sales
sales[sales>500]
sales.to_dict()

{'pen': 120, 'pencil': 230, 'notebook': 245, 'erasor': 579}

In [87]:
# 30. Analyse the following code and answer all parts: (a) What is the index order of s? (b) Which label contains NaN? (c) What will the Boolean filter s[s &gt; 20] return? (d) What will pd.notnull(s) indicate for each label? (e) What are the Series name and index name after the final two statements?
data = {'A': 15, 'B': 35, 'C': 25}
s = Series(data, index=['C', 'A', 'D', 'B'])

s.name = 'Observations'
s.index.name = 'Category'